### ISSUE TITLE
The name of the package is 'husarion_office_gz' but the repository name is 'gazebo_worlds'

### ISSUE THREAD

**Issue by rfzeg** [husarion/gazebo_worlds#2]
One difficulty that can arise when working with the 'husarion_office_gz' package is the inconsistency between the package name and the repository name. When cloning the repository, a directory named 'gazebo_worlds' is created, which can be confusing for those expecting to find the 'husarion_office_gz' package directly.

This inconsistency can make it difficult to navigate the ROS workspace and locate the necessary files, **especially for beginners who may not be familiar with the organization of ROS packages**. It can lead to confusion and frustration, and potentially slow down the development process.

To avoid this issue, it may be helpful to ensure that the repository name matches the package name to maintain consistency and make it easier for users to locate the relevant files within the ROS workspace.

**Comment by Kotochleb** [comment]
@rfzeg sorry for such late response. We renamed the repo to match what asked for
